name = "samv71_config"
description = "Contains the configuration variables for the SAMV71 line of MCUs"
version = "0.1.0-dev"
licenses = "BSD-3-Clause"

tags = ["embedded", "samv71"]
website = "https://github.com/scs-cdh/samv71_config"

authors = ["Space Concordia"]
maintainers = ["Thomas Pedneault <thomas@pedneault.dev>"]
maintainers-logins = ["scs-cdh"]

[configuration.variables]
mcu = { type = "Enum", values = ["samv71q21b"], default = "samv71q21b" }
runtime = { type = "Enum", values = ["embedded", "light", "light_tasking"], default = "light_tasking" }
